<?php


namespace app\components;


use Yii;
use yii\httpclient\Client;

class PrivateBankClient extends Client
{
    public function init(){
        parent::init();
        $this->baseUrl = Yii::$app->params['privateBank']['baseUrl'];
    }

    public function get($url, $data = null, $headers = [], $options = [])
    {
//        Yii::$app->response->format = self::FORMAT_JSON;
        return parent::get($url, $data, $headers, $options); // TODO: Change the autogenerated stub
    }
}