<?php
namespace app\components;

use Yii;
use yii\httpclient\Client;
use yii\web\Response;

class SourceCurrencyInfoTarget extends Client
{
//    private $url;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        $this->url = Yii::$app->params['CurrencyRate']['baseUrl'];
        $this->baseUrl = 'https://api.privatbank.ua/';
    }

    public function get($url, $data = null, $headers = [], $options = [])
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return parent::get($url, $data, $headers, $options);
    }

}